services:
  windows-11:
    image: dockurr/windows
    container_name: windows-11
    environment:
      VERSION: "win11"
      LANGUAGE: "Portuguese"
    volumes:
      - ./shared:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

  windows-10:
    image: dockurr/windows
    container_name: windows-10
    environment:
      VERSION: "win10"
      LANGUAGE: "Portuguese"
    volumes:
      - ./shared:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

  windows-8:
    image: dockurr/windows
    container_name: windows-8
    environment:
      VERSION: "win8"
      LANGUAGE: "Portuguese"
    volumes:
      - ./shared:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m

  windows-7:
    image: dockurr/windows
    container_name: windows-7
    environment:
      VERSION: "win7"
      LANGUAGE: "Portuguese"
    volumes:
      - ./shared:/shared
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m